# Based on original gist by aiden1999
# Source: https://gist.github.com/aiden1999/509a54e7665c6da1b115c24686eac14c
# Modified by wtchrs on 2025-12-11

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ÓÇ∂](nord10)\
$os$username[@](bg:nord10 fg:nord0)$hostname\
[ÓÇ∞](bg:nord9 fg:nord10)\
$directory\
[ÓÇ∞](bg:nord8 fg:nord9)\
$git_branch$git_metrics$git_status\
[ÓÇ∞](bg:nord7 fg:nord8)\
$package$c$cmake$deno$dotnet$elixir$erlang$gleam$golang$haskell\
$helm$java$julia$kotlin$gradle$lua$nodejs$php$python$ruby$rust\
$scala$swift$terraform$typst$vagrant$zig\
[ÓÇ∞](bg:nord4 fg:nord7)\
$cmd_duration\
[ÓÇ∞](fg:nord4)\
$line_break\
$character
"""

continuation_prompt = "[ ÔÑÅ ](#62708a)"

palette = 'nord'

[palettes.nord]
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
nord4 = '#D8DEE9'
nord5 = '#E5E9F0'
nord6 = '#ECEFF4'
nord7 = '#8FBCBB'
nord8 = '#88C0D0'
nord9 = '#81A1C1'
nord10 = '#5E81AC'
nord11 = '#BF616A'
nord13 = '#EBCB8B'
nord14 = '#A2BE8A'

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "Û∞ò¨ "
style = "fg:nord0 bg:nord8"

[git_metrics]
format = '[+$added/-$deleted ](fg:nord0 bg:nord8)'
disabled = false

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "fg:nord0 bg:nord8"

# LANGUAGES
# =========

[c]
symbol = "Óòû "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[cmake]
symbol = "Û∞î∑ "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[deno]
symbol = "ü¶ï "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[dotnet]
symbol = "Óùø "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[elixir]
symbol = "Óò≠ "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[erlang]
symbol = "Óû± "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[gleam]
symbol = "‚≠ê "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[golang]
symbol = "Óòß "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[haskell]
symbol = "Óòü "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[helm]
symbol = "‚éà "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[java]
symbol = "Óú∏ "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[julia]
symbol = "Óò§ "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[kotlin]
symbol = "Óò¥ "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[gradle]
symbol = "Óô† "
format = "[ $symbol ]($style)"
style = "fg:nord0 bg:nord7"

[lua]
symbol = 'Û∞¢± '
format = '[ $symbol($version )]($style)'
style = "fg:nord0 bg:nord7"

[python]
symbol = 'Û∞å† '
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[nodejs]
symbol = "Óúò "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[php]
symbol = "Óòà "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[ruby]
symbol = "Óûë "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[rust]
symbol = "Óû® "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[scala]
symbol = "Óú∑ "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[swift]
symbol = "Óùï "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[terraform]
symbol = "Óöö "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[typst]
symbol = "ÔÖõ "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[vagrant]
symbol = "Óö¨ "
format = "[ $symbol ]($style)"
style = "fg:nord0 bg:nord7"

[zig]
symbol = "Óö© "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[package]
symbol = "Û∞èó "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:nord0 bg:nord10"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = "Ó¨Å "

[os]
style = "fg:nord0 bg:nord10"
disabled = false

[os.symbols]
Arch = 'ÔåÉ '

[shell]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:nord0 bg:nord10"

[directory]
style = "fg:nord0 bg:nord9"
read_only = "Ó©µ "
format = "[ Û∞âã $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:nord0 bold bg:nord9"

[sudo]
disabled = false
symbol = "Ôìü "
style = "fg:nord0 bg:nord4"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ Û∞îö $duration ]($style)"
style = "fg:nord0 bg:nord4"

[character]
success_symbol = "[ ‚Ä¢](bold green)"
error_symbol = "[ ‚Ä¢](bold red)"
vimcmd_symbol = "[ Óò´ ‚Ä¢](bold green)"
