[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon-drop -x -i -T "$0"'

[[mgr.prepend_keymap]]
on = ["<Space>", "<Space>"]
run = "toggle"
desc = "Toggle selection"

[[mgr.prepend_keymap]]
on   = ["<Space>", "w"]
for  = "linux"
run  = 'shell -- hyprctl hyprpaper reload ,"$0"'
desc = "Set hovered file as wallpaper"
